### ISSUE TITLE
train.py 报错缺少cudnn

### ISSUE THREAD

**Issue by a00147600** [yeyupiaoling/PPASR#75]
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.
  [Hint: 'CUDNN_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is usually caused by a failure to launch some cuDNN kernel on the GPU, which can occur for multiple reasons.  To correct, check that the hardware, an appropriate version of the driver, and the cuDNN library are correctly installed.  Otherwise, this may indicate an internal error/bug in the library.  ] (at ../paddle/phi/kernels/gpudnn/conv_kernel.cu:379)
  [operator < conv2d > error]
  这段文字貌似提醒我没有cudnn模块，同时还有一大段以下文字。
  Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
Error: ../paddle/phi/kernels/funcs/elementwise_functor.h:545 Assertion `b != 0` failed. InvalidArgumentError: Integer division by zero encountered in (floor) divide. Please check the input value.
是不是同一个问题 我是win环境

**Comment by yeyupiaoling** [comment]
应该是你没有安装CUDNN，或者安装的CUDNN版本不对。你可以用conda安装。命令如下：
```
conda install paddlepaddle-gpu==2.3.0 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
```

**Comment by a00147600** [comment]
谢谢回复 我将这段命令导入后 train.py没有改动 执行python train.py 目前卡在这个界面
(about_ppasr) F:\PPASR-master>python train.py
C:\ProgramData\Anaconda3\envs\about_ppasr\lib\site-packages\librosa\core\constantq.py:1058: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
-----------  Configuration Arguments -----------
alpha: 2.2
augment_conf_path: conf/augmentation.json
batch_size: 32
beam_size: 300
beta: 4.3
cutoff_prob: 0.99
cutoff_top_n: 40
dataset_vocab: dataset/vocabulary.txt
decoder: ctc_greedy
feature_method: linear
lang_model_path: lm/zh_giga.no_cna_cmn.prune01244.klm
learning_rate: 5e-05
max_duration: 20
mean_std_path: dataset/mean_std.npz
metrics_type: cer
min_duration: 0.5
num_epoch: 65
num_proc_bsearch: 10
num_workers: 8
pretrained_model: None
resume_model: None
save_model_path: models/
test_manifest: dataset/manifest.test
train_manifest: dataset/manifest.train
use_model: deepspeech2
------------------------------------------------
dataset/manifest.noise不存在，已经忽略噪声增强操作！
[2022-06-07 09:55:23.711399] 数据增强配置：{'type': 'speed', 'aug_type': 'audio', 'params': {'min_speed_rate': 0.9, 'max_speed_rate': 1.1, 'num_rates': 3}, 'prob': 1.0}
[2022-06-07 09:55:23.711399] 数据增强配置：{'type': 'shift', 'aug_type': 'audio', 'params': {'min_shift_ms': -5, 'max_shift_ms': 5}, 'prob': 1.0}
[2022-06-07 09:55:23.711399] 数据增强配置：{'type': 'volume', 'aug_type': 'audio', 'params': {'min_gain_dBFS': -15, 'max_gain_dBFS': 15}, 'prob': 1.0}
[2022-06-07 09:55:23.711399] 数据增强配置：{'type': 'specaug', 'aug_type': 'feature', 'params': {'W': 0, 'F': 10, 'n_freq_masks': 2, 'T': 50, 'n_time_masks': 2, 'p': 1.0, 'adaptive_number_ratio': 0, 'adaptive_size_ratio': 0, 'max_n_time_masks': 20, 'replace_with_zero': True}, 'prob': 1.0}
C:\ProgramData\Anaconda3\envs\about_ppasr\lib\site-packages\paddle\fluid\reader.py:480: UserWarning: DataLoader with multi-process mode is not supported on MacOs and Windows currently. Please use signle-process mode with num_workers = 0 instead
  warnings.warn(
W0607 09:55:23.715387 76528 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 10.2
W0607 09:55:23.734336 76528 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.

**Comment by a00147600** [comment]
> 应该是你没有安装CUDNN，或者安装的CUDNN版本不对。你可以用conda安装。命令如下：
> 
> ```
> conda install paddlepaddle-gpu==2.3.0 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
> ```

谢谢回复 我执行命令后 执行train.py 依然有不正确参数错误 
OSError: (External) CUDNN error(3), CUDNN_STATUS_BAD_PARAM.
[Hint: 'CUDNN_STATUS_BAD_PARAM'. An incorrect value or parameter was passed to the function. To correct, ensure that all the parameters being passed have valid values. ] (at ..\paddle/fluid/platform/device/gpu/cuda/cudnn_helper.h:287)
[operator < rnn > error]

**Comment by yeyupiaoling** [comment]
你的显卡是什么型号？其他程序正常吗？

**Comment by a00147600** [comment]
> 你的显卡是什么型号？其他程序正常吗？

显卡是3090 装的CUDA版本11.7 create.py 和 infer.py是正常执行的。
(about_ppasr) F:\PPASR-master>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

**Comment by yeyupiaoling** [comment]
哦，30系列的要cuda11以上的，安装这个吧

```
conda install paddlepaddle-gpu==2.3.0 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge 
```

**Comment by a00147600** [comment]
> 

我执行了 然后出现以下问题 我是否需要重新装一遍环境。回到了cudnn的问题
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.
  [Hint: 'CUDNN_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is usually caused by a failure to launch some cuDNN kernel on the GPU, which can occur for multiple reasons.  To correct, check that the hardware, an appropriate version of the driver, and the cuDNN library are correctly installed.  Otherwise, this may indicate an internal error/bug in the library.  ] (at ../paddle/phi/kernels/gpudnn/conv_kernel.cu:379)
  [operator < conv2d > error]

**Comment by a00147600** [comment]
> 哦，30系列的要cuda11以上的，安装这个吧
> 
> ```
> conda install paddlepaddle-gpu==2.3.0 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge 
> ```

我执行了 然后出现以下问题 我是否需要重新装一遍环境。回到了cudnn的问题
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.
[Hint: 'CUDNN_STATUS_EXECUTION_FAILED'. The GPU program failed to execute. This is usually caused by a failure to launch some cuDNN kernel on the GPU, which can occur for multiple reasons. To correct, check that the hardware, an appropriate version of the driver, and the cuDNN library are correctly installed. Otherwise, this may indicate an internal error/bug in the library. ] (at ../paddle/phi/kernels/gpudnn/conv_kernel.cu:379)
[operator < conv2d > error]

**Comment by yeyupiaoling** [comment]
你试试这个能否通过检查
```
paddle.utils.run_check()
```

**Comment by a00147600** [comment]
> 你试试这个能否通过检查
> 
> ```
> paddle.utils.run_check()
> ```

可以的
(about_ppasr) F:\PPASR-master>python
Python 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0607 11:49:30.111837 76260 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.2
W0607 11:49:30.117821 76260 gpu_context.cc:306] device: 0, cuDNN Version: 8.2.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
>>>

**Comment by yeyupiaoling** [comment]
这就奇怪了，你运行过其他的Paddle项目吗，有没有报这个错误？

**Comment by a00147600** [comment]
> 这就奇怪了，你运行过其他的Paddle项目吗，有没有报这个错误？

不好意思 您这个项目是我第一次接触paddle 我在想是不是我的环境出现了重复导入的问题 在想要不要重来一遍。。

**Comment by yeyupiaoling** [comment]
你用conda 重新创建一个虚拟环境，Python为3.7的试试

**Comment by a00147600** [comment]
> 这就奇怪了，你运行过其他的Paddle项目吗，有没有报这个错误？

不好意思 您这个项目是我第一次接触paddle 我在想是不是我的环境出现了重复导入的问题 在想要不要重来一遍。。

**Comment by a00147600** [comment]
> 你用conda 重新创建一个虚拟环境，Python为3.7的试试

重建3.7环境后 安装命令 
python setup.py install 
python -m pip install ppasr -U
conda install paddlepaddle-gpu==2.3.0 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge 

之后 执行 train以及其他文件出现 OSError: sndfile library not found
看了下解决办法基本围绕linux  之前第一次安装并没有出现这个问题
OSError: cannot load library 'C:\ProgramData\Anaconda3\envs\ppasr\lib\site-packages\soundfile-0.10.3.post1-py3.7.egg\_soundfile_data\libsndfile64bit.dll': error 0x7e

**Comment by yeyupiaoling** [comment]
https://blog.csdn.net/byna11sina11/article/details/109676427

**Comment by a00147600** [comment]
> https://blog.csdn.net/byna11sina11/article/details/109676427
谢谢 这篇文章解决了这个问题。我回到之前的train.py 熟悉的报错环节了
对这个问题 我现在在看这篇文章不知道有没有帮助 另外这个conda下载较慢 https://blog.csdn.net/u013128836/article/details/101636736?ops_request_misc=&request_id=&biz_id=102&utm_term=The%20GPU%20program%20failed%20to%20exec&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduweb~default-1-101636736.142^v11^pc_search_result_control_group,157^v13^new_style2&spm=1018.2226.3001.4187

OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.
  [Hint: 'CUDNN_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is usually caused by a failure to launch some cuDNN kernel on the GPU, which can occur for multiple reasons.  To correct, check that the hardware, an appropriate version of the driver, and the cuDNN library are correctly installed.  Otherwise, this may indicate an internal error/bug in the library.  ] (at ../paddle/phi/kernels/gpudnn/conv_kernel.cu:379)
  [operator < conv2d > error]

**Comment by a00147600** [comment]
> https://blog.csdn.net/byna11sina11/article/details/109676427

不好意思又打扰了 烦请了解下您的显卡 nvidia版本 cuda cudnn版本好吗？
我似乎找到了自己出错的原因 跟这位博主的说法一致
https://blog.csdn.net/hunterflyy/article/details/108369274?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522165475452316781483711035%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=165475452316781483711035&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_ecpm_v1~rank_v31_ecpm-1-108369274-null-null.142^v11^pc_search_result_control_group,157^v13^new_style2&utm_term=unspecified+launch+failure+719&spm=1018.2226.3001.4187

**Comment by yeyupiaoling** [comment]
我的是2080ti
驱动版本510
CUDA 10.2
cudnn 7.6.5

**Comment by yeyupiaoling** [comment]
30系显卡的驱动好像不能低于450还是470
